# Generated by Django 5.2.5 on 2025-08-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(max_length=255, verbose_name='テーマ文')),
                ('theme_detail', models.TextField(verbose_name='テーマ詳細')),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='ディベート部屋名')),
                ('room_start', models.DateTimeField(auto_now_add=True, verbose_name='ディベート開始日時')),
                ('room_end', models.DateTimeField(verbose_name='ディベート終了日時')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rooms', to='user.user', verbose_name='作成者')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='debate.theme', verbose_name='テーマ')),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
