# Generated by Django 5.2.5 on 2025-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_participate'),
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='participating_rooms', through='debate.Participate', to='user.user'),
        ),
    ]
