# Generated by Django 5.2.5 on 2025-08-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_room_participants'),
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='コメント文')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='debate.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.user')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['post_date'],
            },
        ),
        migrations.CreateModel(
            name='CommentReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_timestamp', models.DateTimeField(auto_now=True, verbose_name='最終既読時間')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'comment_read_status',
                'unique_together': {('sender', 'room')},
            },
        ),
    ]
