# Generated by Django 5.2.5 on 2025-08-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_comment_commentreadstatus'),
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreadstatus',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='commentreadstatus',
            unique_together={('user', 'room')},
        ),
        migrations.AddField(
            model_name='commentreadstatus',
            name='last_read_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.comment'),
        ),
        migrations.RemoveField(
            model_name='commentreadstatus',
            name='last_read_timestamp',
        ),
    ]
