# Generated by Django 5.2.5 on 2025-08-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_rename_sender_commentreadstatus_user_and_more'),
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(verbose_name='要約文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='debate.room')),
            ],
            options={
                'db_table': 'ai_feedback_summary',
            },
        ),
        migrations.CreateModel(
            name='AIFeedbackPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='フィードバック文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_feedbacks', to='debate.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_feedbacks', to='user.user')),
            ],
            options={
                'db_table': 'ai_feedback_private',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
