# Generated by Django 5.2.4 on 2025-07-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
    ]
