# Generated by Django 5.2.4 on 2025-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(max_length=50, unique=True, verbose_name='ClerkユーザーID')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='ユーザー名')),
                ('first_flag', models.BooleanField(default=True, verbose_name='初回ログインフラグ')),
                ('deleted_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='退会日時')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
