# Generated by Django 5.2.5 on 2025-08-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True, verbose_name='メールアドレス'),
            preserve_default=False,
        ),
    ]
